# Generated by Django 4.2.2 on 2023-06-19 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_comment_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['id']},
        ),
    ]
